services:
  - type: web
    name: django-ecommerce-api
    env: python
    rootDir: E-commerce Backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
    startCommand: "gunicorn core.wsgi:application"
